const toastrSettings = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": false,
    "progressBar": false,
    "positionClass": "toast-bottom-right",
    "preventDuplicates": true,
    "onclick": null,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "3000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
    // "closeButton": false,
    // "debug": false,
    // "newestOnTop": false,
    // "progressBar": false,
    // "positionClass": "toast-bottom-right",
    // "preventDuplicates": false,
    // "onclick": null,
    // "showDuration": "300",
    // "hideDuration": "1000",
    // "timeOut": 0,
    // "extendedTimeOut": 0,
    // "showEasing": "swing",
    // "hideEasing": "linear",
    // "showMethod": "fadeIn",
    // "hideMethod": "fadeOut",
    // "tapToDismiss": false
};

export default toastrSettings;